# Generated by Django 4.1.2 on 2022-10-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "inputAudioPath",
                    models.FileField(null=True, upload_to="audio/", verbose_name=""),
                ),
                (
                    "outputTextPath",
                    models.FileField(null=True, upload_to="text/", verbose_name=""),
                ),
            ],
        ),
    ]
