# Generated by Django 4.1.2 on 2022-10-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="outputTextPath",),
        migrations.AddField(
            model_name="user", name="outputText", field=models.TextField(default=""),
        ),
    ]
