# Generated by Django 4.1.2 on 2022-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_remove_user_outputtextpath_user_outputtext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="inputAudioPath",
            field=models.FileField(
                default="test.waf", upload_to="audio/", verbose_name=""
            ),
        ),
    ]
